# Generated by Django 5.2.3 on 2025-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('drinks', 'Drinks'), ('snacks', 'Snacks')], default='snacks', max_length=20),
        ),
    ]
