# Generated by Django 4.2.7 on 2025-10-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_create_default_items_with_urlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
